# RT-Thread building script for Gui Engine

from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('GuiEngine', src, depend = ['GUIENGINE_IMAGE_TJPGD'], CPPPATH = CPPPATH)

Return('group')
