# RT-Thread building script for Gui Engine

from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [ cwd,
			cwd + '/rtgui',
			cwd + '/rtgui/widgets']

group = DefineGroup('GuiEngine', src, depend = [''], CPPPATH = CPPPATH)

Return('group')